// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sesleusxaskzjtlifzgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc2xldXN4YXNremp0bGlmemdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NjA5NTgsImV4cCI6MjA5MTEzNjk1OH0.rn13C_og0zUNt1IX-Vl7jN5KsA9_sL3L8Jvf4d5ufjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});